### ISSUE TITLE
if the hand is out of frame

### ISSUE THREAD

**Issue by ghost** [keijiro/HandPoseBarracuda#16]
how can I make the hand disappear when it leaves the frame?

**Comment by keijiro** [comment]
At first, you have to design a strategy to determine the hand state (shown/hidden).

Thresholding with the hand detector score? Or using the scores from the hand landmark detector? Or detecting jumps with the detected region?

Then you can implement one of them in the pipeline.

I didn't implement it because I thought that there is no best strategy for it.

**Comment by keijiro** [comment]
I'm closing this issue as answered. Please reopen it for further problems.
